name: My API app
port: 8080
public: public
path: /api
authentication: jwtAuth # or apiKeyAuth
database: mysql
models:
  - users:
    - table users:
        get:
          - int id
          - varchar username
          - varchar email
        get /users/:id:
          - int id PK
          - varchar username
          - varchar email
          - datetime created_at
          - datetime updated_at
        post*:
          - varchar username
          - varchar email
        put* /users/:id:
          - int id PK
          - varchar username
          - varchar email
        delete* /users/:id:
          - int id PK
        patch* /users/:id/username:
          - int id PK
          - varchar username
        patch* /users/:id/email:
          - int id PK
          - varchar email

    - procedure usp_update_user:
        post*:
          - int id
          - varchar username
          - varchar email
          - datetime created_at
          - datetime updated_at


