version: 1.0
name: My API app
port: 8080
public: public
base: /api
api:
  - path: /hello
    methods: get, post, put, delete, patch
    name: hello
    type: mssql:table
    fields:
      - int id PK "autoincrement"
      - varchar name
      - varchar email
      - datetime created_at
      - datetime updated_at


  - path: /company-person
    id: companyId
    methods: get
    name: CompanyPersonEmployeeType A
          INNER JOIN CompanyPerson CP ON CP.CompanyPersonID = A.CompanyPersonID
          INNER JOIN Company C ON CP.CompanyID = C.CompanyID
    type: mssql:table
    fields:
      - int CP.CompanyID PK
      - int CP.CompanyPersonID
      - string A.EmployeeTypeCt
      - datetime StartDate
      - datetime EndDate



