version: 1.0
name: My API app
port: 8080
public: public
base: /api
entities:
  - path: /user
    path_plural: /users
    type: table
    name: user
    fields:
      - int id PK "autoincrement"
      - varchar name
      - varchar email
      - datetime created_at
      - datetime updated_at
    methods: get, post, put, delete, patch

  - path: /company-person
    type: query
    name: CompanyPerson
    from: CompanyPersonEmployeeType A
          INNER JOIN CompanyPerson CP ON CP.CompanyPersonID = A.CompanyPersonID
          INNER JOIN Company C ON CP.CompanyID = C.CompanyID
    fields:
      - int CP.CompanyID PK
      - int CP.CompanyPersonID
      - string A.EmployeeTypeCt
      - datetime StartDate
      - datetime EndDate
    id: companyId

  - path: /update_user
    type: stored procedure
    name: usp_update_user
    fields:
      - int id PK "autoincrement"
      - varchar name
      - varchar email
      - datetime created_at
      - datetime updated_at



