version: "1.0"
name: My API app
port: 8080
public: public
path: /api
authentication: jwtAuth # or apiKeyAuth
databases:
  - type: mssql
    name: mydb
    objects:
      - table: users
        get:
          - int id
          - varchar name
          - varchar email
        get-id:
          - int id PK
          - varchar name
          - varchar email
          - datetime created_at
          - datetime updated_at
        post*:
          - varchar name
          - varchar email
        put*:
          - int id PK
          - varchar name
          - varchar email
        delete*:
          - int id PK
        patch-name*:
          - int id PK
          - varchar name
        patch-email*:
          - int id PK
          - varchar email

      - procedure: usp_update_user
        post*:
          - int id
          - varchar name
          - varchar email
          - datetime created_at
          - datetime updated_at

      - query: users_posts
        select: select * from users u join posts p on u.id = p.user_id
        get:
        get-byUser:
          - int id SK "u.id"


