version: 1.0
name: My API app
port: 8080
public: public
path: /api
entities:
  - type: table
    name: user
    fields:
      - int id PK "autoincrement"
      - varchar name PK
      - varchar email
      - datetime created_at
      - datetime updated_at
    methods: get, post, put, delete, patch

  - type: query
    name: CompanyPerson
    query: SELECT
            CP.CompanyID,
            CP.CompanyPersonID,
            A.EmployeeTypeCt,
            CONVERT(NCHAR(8),[StartDate],112) as 'StartDate',
            CONVERT(NCHAR(8),[EndDate],112) as 'EndDate'
          FROM CompanyPersonEmployeeType A
          INNER JOIN CompanyPerson CP ON CP.CompanyPersonID = A.CompanyPersonID
          INNER JOIN Company C ON CP.CompanyID = C.CompanyID AND A.StartDate >= C.AuditDate
    fields:
      - int CompanyID

  - type: stored procedure
    name: usp_update_user
    fields:
      - int id
      - varchar name
      - varchar email
      - datetime created_at
      - datetime updated_at



