version: 1.0
name: My API app
port: 8080
public: public
base: /api
entities:
  - path: /hello
    methods: get, post, put, delete, patch
    name: hello
    fields:
      - int id PK "autoincrement"
      - varchar name
      - varchar email
      - datetime created_at
      - datetime updated_at

  - path: /company-person
    name: CompanyPerson
    from: CompanyPersonEmployeeType A
          INNER JOIN CompanyPerson CP ON CP.CompanyPersonID = A.CompanyPersonID
          INNER JOIN Company C ON CP.CompanyID = C.CompanyID
    fields:
      - int CP.CompanyID PK
      - int CP.CompanyPersonID
      - string A.EmployeeTypeCt
      - datetime StartDate
      - datetime EndDate
    methods: get
    id: companyId



