name: My API app
port: 8080
path: /api
database: mysql
models:
  - name: mydb
    objects:
      - table: users
        get:
          - int id
          - varchar name
          - varchar email
        get /users:id:
          - int id PK
          - varchar name
          - varchar email
        post:
          - varchar name
          - varchar email